package com.lmg.online.chatbot.ai.tools.order.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lmg.online.chatbot.ai.tools.order.dto.ChatbotOrderTrackingResponse.OrderSummary;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response DTO for the CANCEL_OR_RETURN intent.
 *
 * Combines two things the frontend needs:
 *   1. orderData — the specific order the customer wants to cancel/return (may be null)
 *   2. policyText — cancel/return/exchange policy fetched from RAG
 *
 * When the user provides an order number but it is not found / invalid,
 * {@code needsOrderNumber} is set to true and the frontend prompts for
 * a corrected order number while still showing the policy.
 */
@Data
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class CancelReturnResponse {

    /** Error or info message; null when the response has full data. */
    @JsonProperty("chat_message")
    private String chatMessage;

    /**
     * The order the customer wants to cancel/return.
     * Null when no order number was provided OR when the order could not be found.
     */
    @JsonProperty("orderData")
    private OrderSummary orderData;

    /**
     * Cancel / return / exchange policy text generated by AI from RAG context.
     * Always populated (even when order lookup fails) so the customer always
     * gets the policy information.
     */
    @JsonProperty("policyText")
    private String policyText;

    /**
     * True when an order number was present in the message but the order
     * could not be found or was invalid. Signals the frontend to show an
     * order-number input field so the customer can retry with a correct number.
     */
    @JsonProperty("needsOrderNumber")
    private boolean needsOrderNumber;
}
